Repository 9-numble/backend, pull requests merged in 2022-11, with the labels that each got.

#5 배포 서버 환경 설정
  Dockerfile
  build.gradle
  src/main/java/com/project/numble/config/SecurityConfig.java
  src/main/resources/application-db.yml
  src/main/resources/application-jpa.yml
  src/main/resources/application-oauth2.yml
  src/main/resources/application-session.yml
  src/main/resources/application.yml
Labels: ci

#6 User, Animal 관련 Entity 추가
  src/main/java/com/project/numble/application/common/entity/BaseTimeEntity.java
  src/main/java/com/project/numble/application/user/domain/Address.java
  src/main/java/com/project/numble/application/user/domain/Animal.java
  src/main/java/com/project/numble/application/user/domain/AnimalType.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/main/java/com/project/numble/application/user/domain/enums/Role.java
Labels: feat

#8 회원 가입 기능 추가 및 문서화
  build.gradle
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/auth/controller/AuthController.java
  src/main/java/com/project/numble/application/auth/controller/advice/AuthControllerAdvice.java
  src/main/java/com/project/numble/application/auth/dto/request/SignUpRequest.java
  src/main/java/com/project/numble/application/common/advice/CommonControllerAdvice.java
  src/main/java/com/project/numble/application/common/advice/ControllerAdviceUtils.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/repository/UserRepository.java
  src/main/java/com/project/numble/application/user/service/UserService.java
  src/main/java/com/project/numble/application/user/service/exception/UserEmailAlreadyExistsException.java
  src/main/java/com/project/numble/config/SecurityConfig.java
  src/main/java/com/project/numble/config/WebConfig.java
  src/main/java/com/project/numble/core/security/CustomAccessDeniedHandler.java
  src/main/java/com/project/numble/core/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/project/numble/core/security/CustomAuthenticationFilter.java
  src/main/java/com/project/numble/core/security/CustomAuthenticationToken.java
  src/main/java/com/project/numble/core/security/CustomUserDetails.java
  src/main/java/com/project/numble/core/security/CustomUserDetailsService.java
  src/main/java/com/project/numble/core/security/exception/UnsupportedSecurityOperationException.java
  src/main/java/com/project/numble/core/security/oauth2/CustomAuthenticationFailureHandler.java
  src/main/java/com/project/numble/core/security/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/com/project/numble/core/security/oauth2/CustomOAuth2UserService.java
  src/main/java/com/project/numble/core/security/oauth2/attribute/AbstractOAuth2Attribute.java
  src/main/java/com/project/numble/core/security/oauth2/attribute/KakaoOAuth2Attribute.java
  src/main/java/com/project/numble/core/security/oauth2/attribute/NaverOAuth2Attribute.java
  src/main/java/com/project/numble/core/security/oauth2/attribute/OAuth2AttributeFactory.java
  src/main/resources/message/exception_message.properties
  src/main/resources/message/validation_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/auth/controller/AuthControllerDocsTest.java
  src/test/java/com/project/numble/application/helper/factory/dto/SignUpFactory.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: feat, docs

#9 github action workflow 수정
  .github/workflows/github-action-build.yml
Labels: ci

#10 board 관련 기능 추가 및 Entity 추가
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/Category.java
  src/main/java/com/project/numble/application/board/domain/CategoryType.java
  src/main/java/com/project/numble/application/board/domain/Comment.java
  src/main/java/com/project/numble/application/board/domain/Image.java
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/request/ModBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/DelBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/BoardRepository.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/BoardServiceImp.java
  src/main/java/com/project/numble/application/board/service/exception/BoardNotExistsException.java
  src/main/java/com/project/numble/application/user/domain/User.java
Labels: feat

#12 로그인 기능 추가 및 문서화
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/auth/controller/AuthController.java
  src/main/java/com/project/numble/application/auth/controller/advice/AuthControllerAdvice.java
  src/main/java/com/project/numble/application/auth/dto/request/SignInRequest.java
  src/main/java/com/project/numble/application/auth/service/AuthService.java
  src/main/java/com/project/numble/application/auth/service/StandardAuthService.java
  src/main/java/com/project/numble/application/auth/service/exception/SignInFailureException.java
  src/main/java/com/project/numble/application/common/advice/CommonControllerAdvice.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/repository/exception/UserNotFoundException.java
  src/main/java/com/project/numble/config/SecurityConfig.java
  src/main/resources/message/exception_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/auth/controller/AuthControllerDocsTest.java
  src/test/java/com/project/numble/application/helper/factory/dto/SignInFactory.java
Labels: feat, docs

#14 회원 가입 기능 수정
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/auth/controller/advice/AuthControllerAdvice.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/repository/UserRepository.java
  src/main/java/com/project/numble/application/user/service/StandardUserService.java
  src/main/java/com/project/numble/application/user/service/UserService.java
  src/main/java/com/project/numble/application/user/service/exception/UserNicknameAlreadyExistsException.java
  src/main/resources/message/exception_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/auth/controller/AuthControllerDocsTest.java
Labels: docs

#16 BoardService 부분 수정
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/request/ModBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/test/java/com/project/numble/application/board/service/StandardBoardServiceTest.java
Labels: refactor

#17 board 추가시 User List 추가
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/response/DelBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/test/java/com/project/numble/application/board/service/StandardBoardServiceTest.java
Labels: feat, refactor

#18 User Custom ArgumentResolver 추가
  src/main/java/com/project/numble/config/WebConfig.java
  src/main/java/com/project/numble/core/resolver/SignInUser.java
  src/main/java/com/project/numble/core/resolver/SignInUserArgumentResolver.java
  src/main/java/com/project/numble/core/resolver/UserInfo.java
Labels: feat

#20 주소 검색 기능 추가
  Dockerfile
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/controller/UserController.java
  src/main/java/com/project/numble/application/user/controller/advice/UserControllerAdvice.java
  src/main/java/com/project/numble/application/user/dto/response/FindAddressByClientIpResponse.java
  src/main/java/com/project/numble/application/user/dto/response/FindAddressByQueryResponse.java
  src/main/java/com/project/numble/application/user/service/StandardUserService.java
  src/main/java/com/project/numble/application/user/service/UserService.java
  src/main/java/com/project/numble/application/user/service/util/UrlConnectionIOException.java
  src/main/java/com/project/numble/application/user/service/util/UserOpenApiResponseKeyConst.java
  src/main/java/com/project/numble/application/user/service/util/UserOpenApiUrlConst.java
  src/main/resources/application-api.yml
  src/main/resources/application.yml
  src/main/resources/message/exception_message.properties
  src/test/java/com/project/numble/application/user/controller/UserControllerDocsTest.java
Labels: feat, docs

#21 로그아웃 기능 추가
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/auth/controller/AuthController.java
  src/main/java/com/project/numble/application/auth/controller/advice/AuthControllerAdvice.java
  src/main/java/com/project/numble/application/auth/exception/UserAlreadySignOutException.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/resources/message/exception_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/auth/controller/AuthControllerDocsTest.java
Labels: feat, docs

#26 User 엔티티 수정 및 Animal & Address 기능 추가
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/NumbleApplication.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/BoardRepository.java
  src/main/java/com/project/numble/application/user/controller/UserController.java
  src/main/java/com/project/numble/application/user/domain/Address.java
  src/main/java/com/project/numble/application/user/domain/Animal.java
  src/main/java/com/project/numble/application/user/domain/AnimalType.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/main/java/com/project/numble/application/user/domain/enums/AnimalType.java
  src/main/java/com/project/numble/application/user/dto/request/AddAddressRequest.java
  src/main/java/com/project/numble/application/user/dto/request/AddAnimalsRequest.java
  src/main/java/com/project/numble/application/user/dto/response/GetAddressResponse.java
  src/main/java/com/project/numble/application/user/dto/response/GetUserStaticInfoResponse.java
  src/main/java/com/project/numble/application/user/repository/AddressRepository.java
  src/main/java/com/project/numble/application/user/repository/AnimalRepository.java
  src/main/java/com/project/numble/application/user/repository/UserRepository.java
  src/main/java/com/project/numble/application/user/service/StandardUserService.java
  src/main/java/com/project/numble/application/user/service/UserService.java
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/helper/factory/entity/UserFactory.java
  src/test/java/com/project/numble/application/user/controller/UserControllerDocsTest.java
Labels: feat, docs, refactor

#27 게시글 관련 예외처리 및 기능 추가
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/controller/advice/BoardControllerAdvice.java
  src/main/java/com/project/numble/application/board/controller/advice/CommentControllerAdvice.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/BoardRepository.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/board/service/StandardCommentService.java
  src/main/java/com/project/numble/application/board/service/exception/CommentNotInBoard.java
  src/main/java/com/project/numble/application/board/service/exception/CurrentUserNotSameCommentUser.java
  src/main/java/com/project/numble/application/board/service/exception/CurrentUserNotSameWriter.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/main/resources/message/exception_message.properties
  src/test/java/com/project/numble/application/board/service/StandardBoardServiceTest.java
Labels: feat

#28 로그인 로그 관리 기능 추가
  src/main/java/com/project/numble/application/auth/repository/SignInLogRedisRepository.java
  src/main/java/com/project/numble/application/auth/repository/SignInLogRepository.java
  src/main/java/com/project/numble/application/auth/service/StandardAuthService.java
  src/main/java/com/project/numble/application/user/dto/response/GetUserStaticInfoResponse.java
  src/main/java/com/project/numble/application/user/service/StandardUserService.java
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/user/controller/UserControllerDocsTest.java
Labels: feat, refactor

#29 내 동네 등록 / 반려동물 등록 문서화
  src/docs/asciidoc/docs.adoc
  src/main/resources/message/validation_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/helper/factory/dto/AddAddressRequestFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/AddAnimalsRequestFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/GetAddressResponseFactory.java
  src/test/java/com/project/numble/application/user/controller/UserControllerDocsTest.java
Labels: docs

#30 회원 탈퇴, 내 프로필 조회 기능 추가
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/auth/controller/advice/AuthControllerAdvice.java
  src/main/java/com/project/numble/application/auth/exception/WithdrawalUserException.java
  src/main/java/com/project/numble/application/auth/service/StandardAuthService.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/controller/UserController.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/main/java/com/project/numble/application/user/dto/response/GetMyInfoResponse.java
  src/main/java/com/project/numble/application/user/service/StandardUserService.java
  src/main/java/com/project/numble/application/user/service/UserService.java
  src/main/resources/message/exception_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/auth/controller/AuthControllerDocsTest.java
  src/test/java/com/project/numble/application/helper/factory/dto/GetMyInfoResponseFactory.java
  src/test/java/com/project/numble/application/user/controller/UserControllerDocsTest.java
Labels: feat, docs, refactor

#31 board 카테고리 및 주소 추가
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/BoardAnimal.java
  src/main/java/com/project/numble/application/board/domain/Category.java
  src/main/java/com/project/numble/application/board/domain/CategoryType.java
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/request/ModBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/test/java/com/project/numble/application/board/service/StandardCommentServiceTest.java
Labels: refactor

#33 좋아요 기능 추가
  src/main/java/com/project/numble/application/board/controller/LikeController.java
  src/main/java/com/project/numble/application/board/controller/advice/LikeControllerAdvice.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/Like.java
  src/main/java/com/project/numble/application/board/repository/LikeRepository.java
  src/main/java/com/project/numble/application/board/service/LikeService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/board/service/StandardLikeService.java
  src/main/java/com/project/numble/application/board/service/exception/AlreadyLikeBoardException.java
  src/main/java/com/project/numble/application/board/service/exception/LikeNotExistsException.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/resources/message/exception_message.properties
Labels: feat

#34 User 정적 정보 조회 시 프로필 정보 추가
  src/main/java/com/project/numble/application/user/dto/response/GetUserStaticInfoResponse.java
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/user/controller/UserControllerDocsTest.java
Labels: docs, refactor

#35 feat : 좋아요 게시글 표시
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/Like.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/BoardRepository.java
  src/main/java/com/project/numble/application/board/repository/LikeRepository.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/LikeService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/board/service/StandardLikeService.java
Labels: help wanted

#36 Board 엔티티에 like count 추가
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/board/service/StandardLikeService.java
Labels: refactor

#37 feat : 조회수 추가
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
Labels: feat

#38 bookmark 기능 추가 및 기존 코드 수정
  src/main/java/com/project/numble/application/board/controller/BookmarkController.java
  src/main/java/com/project/numble/application/board/controller/advice/BookmarkControllerAdvice.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/Bookmark.java
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/BookmarkRepository.java
  src/main/java/com/project/numble/application/board/repository/LikeRepository.java
  src/main/java/com/project/numble/application/board/service/BookmarkService.java
  src/main/java/com/project/numble/application/board/service/LikeService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/java/com/project/numble/application/board/service/StandardBookmarkService.java
  src/main/java/com/project/numble/application/board/service/StandardLikeService.java
  src/main/java/com/project/numble/application/board/service/exception/AlreadyBookmarkBoardException.java
  src/main/java/com/project/numble/application/board/service/exception/BookmarkNotExistsException.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/resources/banner.txt
  src/main/resources/message/exception_message.properties
Labels: feat

#39 댓글 / 대댓글 기능 리펙토링
  build.gradle
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/board/controller/CommentController.java
  src/main/java/com/project/numble/application/board/controller/advice/CommentControllerAdvice.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/Comment.java
  src/main/java/com/project/numble/application/board/domain/ReComment.java
  src/main/java/com/project/numble/application/board/dto/request/AddCommentRequest.java
  src/main/java/com/project/numble/application/board/dto/request/ModCommentRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetCommentResponse.java
  src/main/java/com/project/numble/application/board/repository/CommentRepository.java
  src/main/java/com/project/numble/application/board/service/CommentService.java
  src/main/java/com/project/numble/application/board/service/StandardCommentService.java
  src/main/java/com/project/numble/application/comment/controller/CommentController.java
  src/main/java/com/project/numble/application/comment/controller/advice/CommentControllerAdvice.java
  src/main/java/com/project/numble/application/comment/domain/Comment.java
  src/main/java/com/project/numble/application/comment/dto/request/AddCommentRequest.java
  src/main/java/com/project/numble/application/comment/dto/request/ChildrenCommentsRequest.java
  src/main/java/com/project/numble/application/comment/dto/request/GetCommentsRequest.java
  src/main/java/com/project/numble/application/comment/dto/request/GetRootCommentsRequest.java
  src/main/java/com/project/numble/application/comment/dto/request/ModCommentRequest.java
  src/main/java/com/project/numble/application/comment/dto/request/ReplyCommentRequest.java
  src/main/java/com/project/numble/application/comment/dto/response/ChildCommentResponse.java
  src/main/java/com/project/numble/application/comment/dto/response/ChildrenCommentsResponse.java
  src/main/java/com/project/numble/application/comment/dto/response/GetCommentResponse.java
  src/main/java/com/project/numble/application/comment/dto/response/GetCommentsResponse.java
  src/main/java/com/project/numble/application/comment/dto/response/RootCommentResponse.java
  src/main/java/com/project/numble/application/comment/dto/response/RootsCommentsResponse.java
  src/main/java/com/project/numble/application/comment/repository/CommentRepository.java
  src/main/java/com/project/numble/application/comment/repository/CustomCommentRepository.java
  src/main/java/com/project/numble/application/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/project/numble/application/comment/service/CommentService.java
  src/main/java/com/project/numble/application/comment/service/StandardCommentService.java
  src/main/java/com/project/numble/application/comment/service/exception/CommentNotAuthException.java
  src/main/java/com/project/numble/application/comment/service/exception/CommentNotFoundException.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/user/domain/User.java
  src/main/java/com/project/numble/config/JPAConfig.java
  src/main/resources/message/exception_message.properties
  src/main/resources/message/validation_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/board/service/StandardCommentServiceTest.java
  src/test/java/com/project/numble/application/comment/controller/CommentControllerTest.java
  src/test/java/com/project/numble/application/helper/factory/dto/AddCommentRequestFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/GetCommentResponseFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/ModCommentRequestFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/ReplyCommentRequestFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/RootCommentResponseFactory.java
Labels: feat, docs, refactor

#40 이미지 AWS 리펙토링
  Dockerfile
  build.gradle
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/domain/Image.java
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/request/ModBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/common/advice/ExceptionType.java
  src/main/java/com/project/numble/application/image/controller/ImageController.java
  src/main/java/com/project/numble/application/image/controller/advice/ImageControllerAdvice.java
  src/main/java/com/project/numble/application/image/domain/Image.java
  src/main/java/com/project/numble/application/image/domain/exception/UnsupportedImageFormatException.java
  src/main/java/com/project/numble/application/image/dto/request/AddImageRequest.java
  src/main/java/com/project/numble/application/image/dto/request/DelImageRequest.java
  src/main/java/com/project/numble/application/image/dto/response/AddImageResponse.java
  src/main/java/com/project/numble/application/image/dto/response/AddImagesResponse.java
  src/main/java/com/project/numble/application/image/dto/response/DelImageResponse.java
  src/main/java/com/project/numble/application/image/dto/response/GetImagePathResponse.java
  src/main/java/com/project/numble/application/image/repository/ImageRepository.java
  src/main/java/com/project/numble/application/image/service/AwsImageService.java
  src/main/java/com/project/numble/application/image/service/ImageService.java
  src/main/java/com/project/numble/application/image/service/ImageUtils.java
  src/main/java/com/project/numble/application/image/service/S3ImageUtils.java
  src/main/java/com/project/numble/application/image/service/exception/CannotUploadImageException.java
  src/main/java/com/project/numble/application/image/service/exception/ImageNotFoundException.java
  src/main/java/com/project/numble/config/AwsConfig.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
  src/main/resources/message/exception_message.properties
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/helper/factory/dto/ImageDtoFactory.java
  src/test/java/com/project/numble/application/image/controller/ImageControllerTest.java
Labels: feat, docs, refactor

#41 board 조회 페이징 추가
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/repository/BoardRepository.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepository.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepositoryImpl.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
Labels: feat

#42 Image Board 기반 검색 기능 추가
  src/main/java/com/project/numble/application/image/repository/ImageRepository.java
Labels: feat

#43 refactor : list 검색기능 구현
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepository.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepositoryImpl.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
Labels: refactor

#44 게시글 등록 시 이미지 추가 방식 변경
  src/main/java/com/project/numble/application/board/controller/BookmarkController.java
  src/main/java/com/project/numble/application/board/controller/advice/BoardControllerAdvice.java
  src/main/java/com/project/numble/application/board/domain/Board.java
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
Labels: refactor

#45 북마크, 좋아요 기능 문서화
  src/docs/asciidoc/docs.adoc
  src/test/java/com/project/numble/application/board/controller/BookmarkControllerTest.java
  src/test/java/com/project/numble/application/board/controller/LikeControllerTest.java
  src/test/java/com/project/numble/application/board/service/StandardBoardServiceTest.java
Labels: docs

#46 Board 관련 문서화
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/request/ModBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/test/java/com/project/numble/application/board/controller/BoardControllerTest.java
  src/test/java/com/project/numble/application/board/controller/BookmarkControllerTest.java
  src/test/java/com/project/numble/application/board/controller/LikeControllerTest.java
  src/test/java/com/project/numble/application/helper/factory/dto/AddBoardRequestFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/GetAllBoardResponseFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/GetBoardResponseFactory.java
  src/test/java/com/project/numble/application/helper/factory/dto/ModBoardRequestFactory.java
Labels: docs, refactor

#47 refactor : getBoardRequest에 image 추가
  src/main/java/com/project/numble/application/board/dto/request/AddBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/request/ModBoardRequest.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/dto/response/GetBoardResponse.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
Labels: refactor

#49 내가 작성한 댓글 조회 불필요한 snippet 삭제
  src/docs/asciidoc/docs.adoc
  src/main/resources/static/docs/docs.html
Labels: docs

#51 Spring Security Default Login Page 비활성화
  src/main/java/com/project/numble/config/SecurityConfig.java
  src/main/java/com/project/numble/core/security/oauth2/CustomLoginFailureEntryPoint.java
Labels: refactor

#52 AOP 기반 Logger 추가
  src/main/java/com/project/numble/core/aop/aspect/LogTraceAspect.java
  src/main/java/com/project/numble/core/aop/trace/AopLogTrace.java
  src/main/java/com/project/numble/core/aop/trace/LogTrace.java
  src/main/java/com/project/numble/core/aop/trace/TraceId.java
  src/main/java/com/project/numble/core/aop/trace/TraceStatus.java
Labels: feat

#53 애플리케이션 시간대 설정
  Dockerfile
Labels: ci

#54 refactor : board 조회 페이징 변경
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/dto/response/GetAllBoardResponse.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepository.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepositoryImpl.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/test/java/com/project/numble/application/board/controller/BoardControllerTest.java
  src/test/java/com/project/numble/application/helper/factory/dto/GetAllBoardResponseFactory.java
Labels: refactor

#55 게시글 관련 코드 수정
  src/docs/asciidoc/docs.adoc
  src/main/java/com/project/numble/application/board/controller/BoardController.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepository.java
  src/main/java/com/project/numble/application/board/repository/CustomBoardRepositoryImpl.java
  src/main/java/com/project/numble/application/board/service/BoardService.java
  src/main/java/com/project/numble/application/board/service/StandardBoardService.java
  src/main/resources/static/docs/docs.html
  src/test/java/com/project/numble/application/board/controller/BoardControllerTest.java
Labels: docs, refactor

#56 CORS 설정 일부 변경
  src/main/java/com/project/numble/config/CorsFilter.java
Labels: refactor
